[package]
name = "swiftsync_research"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
kernel = { package = "bitcoinkernel", version = "0.2.0" }
plotters = "0.3.7"
serde = { version = "1.0.228", features = ["derive"] }
